SELECT
		CART_NO,
		ITEM_NO,
		ITEM_NAME,
		NAME,
		BASE_PRICE,
		ITEM_CNT,	
		PAYMENT_PRICE,
		SHIPPING_COST,
		RENAME
FROM
(
	SELECT
		SC.CART_NO,
		SI.NO AS ITEM_NO,
		SI.ITEM_NAME,
		M.NAME,
		ISNULL(SI.BASE_PRICE, 0) AS BASE_PRICE,
		ISNULL(SC.ITEM_CNT, 0) AS ITEM_CNT,	
		ISNULL(SI.BASE_PRICE, 0) * ISNULL(SC.ITEM_CNT, 0) AS PAYMENT_PRICE,
		SI.SHIPPING_COST,
		SIF.RENAME
	FROM STORE_CART AS SC WITH(NOLOCK) 
	INNER JOIN STORE_ITEM AS SI WITH(NOLOCK) ON SI.NO=SC.ITEM_NO
	INNER JOIN MEMBER AS M WITH(NOLOCK) ON M.NO=SC.MEMBER_NO
	INNER JOIN STORE_ITEM_FILE AS SIF WITH(NOLOCK) ON SIF.STORE_ITEM_NO=SI.NO
	WHERE SC.ORDER_YN IS NULL
	AND SC.MEMBER_NO = @MEMBER_NO
) AS aa
