SELECT 
    SC.NO,
    SC.CART_NO,
    SC.MEMBER_NO,
    M.NAME,
    SI.ITEM_NAME,
    SI.BASE_PRICE,
    SC.ITEM_NO,
    SC.ORDER_YN,
    SC.ITEM_CNT,
    SC.REG_DT,
    SC.REG_ID,
    SC.UPD_DT,
    SC.UPD_ID   
    FROM STORE_CART AS SC WITH(NOLOCK)
    INNER JOIN STORE_ITEM AS SI WITH(NOLOCK) ON SI.NO = SC.ITEM_NO
    INNER JOIN MEMBER AS M WITH(NOLOCK) ON SC.MEMBER_NO=M.NO
WHERE SC.MEMBER_NO = 1
AND ORDER_YN IS NULL
