SELECT
	STORE_NO,
	STORE_NAME,
	SUM(PRICE) AS PAY_PRICE
FROM
(
	SELECT 
		SM.NO AS STORE_NO,
		SM.STORE_NAME,
		SI.BASE_PRICE,
		SC.ITEM_CNT,
		SI.BASE_PRICE * SC.ITEM_CNT AS PRICE
	FROM STORE_CART AS SC WITH(NOLOCK)
	INNER JOIN STORE_ITEM AS SI WITH(NOLOCK) ON SI.NO=SC.ITEM_NO
	INNER JOIN STORE_MEMBER AS SM WITH(NOLOCK) ON SM.NO = SI.STORE_MEMBER_NO
	WHERE SC.ORDER_YN IS NULL
	AND SC.MEMBER_NO=@MEMBER_NO
) AS AA
GROUP BY STORE_NO, STORE_NAME