SELECT
	SO.NO,
	SI.ITEM_NAME,
	SOD.ITEM_PRICE,
	SOD.ITEM_CNT,
	SOD.ITEM_PRICE * SOD.ITEM_CNT AS PAY_PRICE,
	SOD.PRINTING_STATUS
FROM STORE_ORDER AS SO WITH(NOLOCK) 
INNER JOIN STORE_ORDER_DETAIL AS SOD WITH(NOLOCK) ON SO.NO=SOD.ORDER_MASTER_NO
INNER JOIN STORE_PAYMENT_HISTORY AS SPH WITH(NOLOCK) ON SPH.ORDER_MASTER_NO=SO.NO
LEFT JOIN STORE_ITEM AS SI WITH(NOLOCK) ON SI.NO=SOD.ITEM_NO
LEFT JOIN STORE_SHIPPING_ADDR AS SSA WITH(NOLOCK) ON SSA.NO=SO.SHIPPING_ADDR_NO
WHERE SO.OID = @OID
ORDER BY SO.REG_DT DESC