SELECT
		CART_NO,
		PRODUCT_DETAIL_NO,
		PRODUCT_NAME,
		NAME,
		FILE_SIZE,
		MATERIAL_VOLUME,
		OBJECT_VOLUME,
		SIZE_X,
		SIZE_Y,
		SIZE_Z,
		TOTAL_PRICE,
		PRODUCT_CNT,	
		PAYMENT_PRICE,
		SHIPPING_PRICE
FROM
(
	SELECT
		SC.CART_NO,
		SC.PRODUCT_DETAIL_NO,
		SP.NAME AS PRODUCT_NAME,
		M.NAME,
		SP.FILE_SIZE,
		SP.MATERIAL_VOLUME,
		SP.OBJECT_VOLUME,
		SP.SIZE_X,
		SP.SIZE_Y,
		SP.SIZE_Z,
		ISNULL(SPD.TOTAL_PRICE, 0) AS TOTAL_PRICE,
		ISNULL(SC.PRODUCT_CNT, 0) AS PRODUCT_CNT,	
		ISNULL(SPD.TOTAL_PRICE, 0) * ISNULL(SC.PRODUCT_CNT, 0) AS PAYMENT_PRICE,
		3000 AS SHIPPING_PRICE
	FROM STORE_CART AS SC WITH(NOLOCK) 
	INNER JOIN STORE_PRODUCT_DETAIL AS SPD WITH(NOLOCK) ON SPD.NO=SC.PRODUCT_DETAIL_NO
	INNER JOIN STORE_PRODUCT AS SP WITH(NOLOCK) ON SP.NO=SPD.PRODUCT_NO
	INNER JOIN MEMBER AS M WITH(NOLOCK) ON M.NO=SC.MEMBER_NO
	LEFT JOIN STORE_MATERIAL AS SM WITH(NOLOCK) ON SM.NO=SPD.MATERIAL_NO
	WHERE SC.ORDER_YN IS NULL
	AND SC.MEMBER_NO = @MEMBER_NO
) AS aa
