SELECT
	SO.NO,
	SP.NAME,
	SOD.PRODUCT_PRICE,
	SOD.PRODUCT_CNT,
	SOD.PRODUCT_PRICE * SOD.PRODUCT_CNT AS PAY_PRICE,
	SOD.PRINTING_STATUS
FROM STORE_ORDER AS SO WITH(NOLOCK) 
INNER JOIN STORE_ORDER_DETAIL AS SOD WITH(NOLOCK) ON SO.NO=SOD.ORDER_MASTER_NO
INNER JOIN STORE_PAYMENT_HISTORY AS SPH WITH(NOLOCK) ON SPH.ORDER_MASTER_NO=SO.NO
LEFT JOIN STORE_PRODUCT_DETAIL AS SPD WITH(NOLOCK) ON SPD.NO=SOD.PRODUCT_DETAIL_NO
INNER JOIN STORE_PRODUCT AS SP WITH(NOLOCK) ON SP.NO=SPD.PRODUCT_NO
LEFT JOIN STORE_SHIPPING_ADDR AS SSA WITH(NOLOCK) ON SSA.NO=SO.SHIPPING_ADDR_NO
WHERE SO.OID = @OID
ORDER BY SO.REG_DT DESC