SELECT
		CART_NO,
		ITEM_NO,
		ITEM_NAME,
		NAME,
		BASE_PRICE,
		ITEM_CNT,	
		PAYMENT_PRICE,
		SHIPPING_COST,
		RENAME,
		STORE_URL,
		STORE_NAME,
		STORE_PROFILE_MSG,
		STORE_NO
FROM
(
	SELECT
		SC.CART_NO,
		SI.NO AS ITEM_NO,
		SI.ITEM_NAME,
		M.NAME,
		ISNULL(SI.BASE_PRICE, 0) AS BASE_PRICE,
		ISNULL(SC.ITEM_CNT, 0) AS ITEM_CNT,	
		ISNULL(SI.BASE_PRICE, 0) * ISNULL(SC.ITEM_CNT, 0) AS PAYMENT_PRICE,
		SI.SHIPPING_COST,
		AA.RENAME,
		SM.STORE_URL,
		SM.STORE_NAME,
		SM.STORE_PROFILE_MSG,
		SM.NO AS STORE_NO
	FROM STORE_CART AS SC WITH(NOLOCK) 
	INNER JOIN STORE_ITEM AS SI WITH(NOLOCK) ON SI.NO=SC.ITEM_NO
	INNER JOIN MEMBER AS M WITH(NOLOCK) ON M.NO=SC.MEMBER_NO
	LEFT JOIN STORE_MEMBER AS SM WITH(NOLOCK) ON SM.NO=SI.STORE_MEMBER_NO
	INNER JOIN 
	(
		SELECT 
			STORE_ITEM_NO,
			RENAME,
			FILE_SIZE,
			IMG_USE_YN,
			THUMB_YN,
			USE_YN
		FROM STORE_ITEM_FILE AS SIF WITH(NOLOCK) 		
		WHERE FILE_SIZE = (SELECT MIN(FILE_SIZE) FROM STORE_ITEM_FILE WHERE STORE_ITEM_NO=SIF.STORE_ITEM_NO) 
		AND IMG_USE_YN='Y' AND THUMB_YN='Y' AND USE_YN='Y'
	) as AA ON AA.STORE_ITEM_NO=SI.NO
	WHERE SC.ORDER_YN IS NULL
	AND SC.MEMBER_NO = @MEMBER_NO
) AS aa
