SELECT 
    SC.NO,
    SC.CART_NO,
    SC.MEMBER_NO,
    M.NAME,
    SP.NAME AS PRODUCT_NAME,
    SPD.TOTAL_PRICE,
    SPD.NO AS PRODUCT_DETAIL_NO,
    SC.ORDER_YN,
    SC.PRODUCT_CNT,
    SC.REG_DT,
    SC.REG_ID,
    SC.UPD_DT,
    SC.UPD_ID   
    FROM STORE_CART AS SC WITH(NOLOCK)
    LEFT JOIN STORE_PRODUCT_DETAIL AS SPD WITH(NOLOCK) ON SC.PRODUCT_DETAIL_NO=SPD.NO
    INNER JOIN STORE_PRODUCT AS SP WITH(NOLOCK) ON SPD.PRODUCT_NO = SP.NO
    INNER JOIN MEMBER AS M WITH(NOLOCK) ON SC.MEMBER_NO=M.NO
WHERE SC.MEMBER_NO = @MEMBER_NO
AND ORDER_YN IS NULL